// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PousadaApp.Infrastructure.Data;

#nullable disable

namespace PousadaApp.Infrastructure.Migrations
{
    [DbContext(typeof(PousadaDbContext))]
    [Migration("20260404172851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PousadaApp.Domain.Entities.CategoriaCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icone");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("categorias_cardapio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icone = "pi pi-glass-water",
                            IdEmpresa = 1,
                            Nome = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            Icone = "pi pi-sun",
                            IdEmpresa = 1,
                            Nome = "Pratos Principais"
                        },
                        new
                        {
                            Id = 3,
                            Icone = "pi pi-bolt",
                            IdEmpresa = 1,
                            Nome = "Petiscos"
                        },
                        new
                        {
                            Id = 4,
                            Icone = "pi pi-heart",
                            IdEmpresa = 1,
                            Nome = "Sobremesas"
                        },
                        new
                        {
                            Id = 5,
                            Icone = "pi pi-star",
                            IdEmpresa = 1,
                            Nome = "Drinks"
                        });
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fechamento");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdReserva");

                    b.ToTable("comandas", (string)null);
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Fantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fantasia");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("url_slug");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fantasia = "Bella Vista",
                            Nome = "Pousada Bella Vista",
                            UrlSlug = "bella-vista"
                        });
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Hospede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("hospedes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Sao Paulo - SP",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "123.456.789-00",
                            Email = "carlos.silva@email.com",
                            IdEmpresa = 1,
                            Nome = "Carlos Alberto Silva",
                            Telefone = "(11) 98765-4321"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Rio de Janeiro - RJ",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "987.654.321-00",
                            Email = "maria.oliveira@email.com",
                            IdEmpresa = 1,
                            Nome = "Maria Fernanda Oliveira",
                            Telefone = "(21) 97654-3210"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Belo Horizonte - MG",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "456.789.123-00",
                            Email = "joao.santos@email.com",
                            IdEmpresa = 1,
                            Nome = "Joao Pedro Santos",
                            Telefone = "(31) 96543-2109"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Curitiba - PR",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "321.654.987-00",
                            Email = "ana.pereira@email.com",
                            IdEmpresa = 1,
                            Nome = "Ana Carolina Pereira",
                            Telefone = "(41) 95432-1098"
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Porto Alegre - RS",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "654.321.987-00",
                            Email = "rafael.costa@email.com",
                            IdEmpresa = 1,
                            Nome = "Rafael Mendes Costa",
                            Telefone = "(51) 94321-0987"
                        },
                        new
                        {
                            Id = 6,
                            Cidade = "Salvador - BA",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "789.123.456-00",
                            Email = "juliana.rocha@email.com",
                            IdEmpresa = 1,
                            Nome = "Juliana Martins Rocha",
                            Telefone = "(71) 93210-9876"
                        },
                        new
                        {
                            Id = 7,
                            Cidade = "Recife - PE",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "234.567.890-00",
                            Email = "fernando.lima@email.com",
                            IdEmpresa = 1,
                            Nome = "Fernando Augusto Lima",
                            Telefone = "(81) 92109-8765"
                        },
                        new
                        {
                            Id = 8,
                            Cidade = "Florianopolis - SC",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "567.890.234-00",
                            Email = "patricia.almeida@email.com",
                            IdEmpresa = 1,
                            Nome = "Patricia Souza Almeida",
                            Telefone = "(48) 91098-7654"
                        });
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.ItemComanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdComanda")
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("id_produto");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProduto");

                    b.ToTable("itens_comanda", (string)null);
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit")
                        .HasColumnName("disponivel");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_url");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disponivel = true,
                            IdCategoria = 1,
                            IdEmpresa = 1,
                            Nome = "Agua Mineral 500ml",
                            Preco = 6.00m
                        },
                        new
                        {
                            Id = 2,
                            Disponivel = true,
                            IdCategoria = 1,
                            IdEmpresa = 1,
                            Nome = "Refrigerante Lata",
                            Preco = 8.00m
                        },
                        new
                        {
                            Id = 3,
                            Disponivel = true,
                            IdCategoria = 1,
                            IdEmpresa = 1,
                            Nome = "Suco Natural de Laranja",
                            Preco = 12.00m
                        },
                        new
                        {
                            Id = 4,
                            Disponivel = true,
                            IdCategoria = 1,
                            IdEmpresa = 1,
                            Nome = "Cerveja Long Neck",
                            Preco = 14.00m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Filé de peixe grelhado com legumes e arroz",
                            Disponivel = true,
                            IdCategoria = 2,
                            IdEmpresa = 1,
                            Nome = "Filé de Peixe Grelhado",
                            Preco = 58.00m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Picanha grelhada com arroz, feijao e farofa",
                            Disponivel = true,
                            IdCategoria = 2,
                            IdEmpresa = 1,
                            Nome = "Picanha na Chapa",
                            Preco = 72.00m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Moqueca com camarao, leite de coco e dende",
                            Disponivel = true,
                            IdCategoria = 2,
                            IdEmpresa = 1,
                            Nome = "Moqueca de Camarao",
                            Preco = 68.00m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Filé de frango empanado com molho e queijo",
                            Disponivel = true,
                            IdCategoria = 2,
                            IdEmpresa = 1,
                            Nome = "Frango Parmegiana",
                            Preco = 48.00m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Batata frita crocante com cheddar e bacon",
                            Disponivel = true,
                            IdCategoria = 3,
                            IdEmpresa = 1,
                            Nome = "Porcao de Batata Frita",
                            Preco = 32.00m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "6 unidades de bolinho de bacalhau artesanal",
                            Disponivel = true,
                            IdCategoria = 3,
                            IdEmpresa = 1,
                            Nome = "Bolinho de Bacalhau",
                            Preco = 38.00m
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Torradas com tomate, manjericao e azeite",
                            Disponivel = true,
                            IdCategoria = 3,
                            IdEmpresa = 1,
                            Nome = "Bruschetta Italiana",
                            Preco = 28.00m
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Selecao de queijos e embutidos artesanais",
                            Disponivel = true,
                            IdCategoria = 3,
                            IdEmpresa = 1,
                            Nome = "Tabua de Frios",
                            Preco = 55.00m
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Pudim caseiro de leite condensado",
                            Disponivel = true,
                            IdCategoria = 4,
                            IdEmpresa = 1,
                            Nome = "Pudim de Leite",
                            Preco = 18.00m
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Bolo de chocolate com sorvete de baunilha",
                            Disponivel = true,
                            IdCategoria = 4,
                            IdEmpresa = 1,
                            Nome = "Petit Gateau",
                            Preco = 28.00m
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Acai com granola, banana e leite condensado",
                            Disponivel = true,
                            IdCategoria = 4,
                            IdEmpresa = 1,
                            Nome = "Acai na Tigela",
                            Preco = 24.00m
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Mousse cremoso de maracuja",
                            Disponivel = true,
                            IdCategoria = 4,
                            IdEmpresa = 1,
                            Nome = "Mousse de Maracuja",
                            Preco = 16.00m
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Cachaca artesanal, limao e acucar",
                            Disponivel = true,
                            IdCategoria = 5,
                            IdEmpresa = 1,
                            Nome = "Caipirinha de Limao",
                            Preco = 22.00m
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Rum, leite de coco e suco de abacaxi",
                            Disponivel = true,
                            IdCategoria = 5,
                            IdEmpresa = 1,
                            Nome = "Pina Colada",
                            Preco = 28.00m
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Rum, hortela, limao, acucar e agua com gas",
                            Disponivel = true,
                            IdCategoria = 5,
                            IdEmpresa = 1,
                            Nome = "Mojito",
                            Preco = 26.00m
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "Gin, agua tonica, limao e especiarias",
                            Disponivel = true,
                            IdCategoria = 5,
                            IdEmpresa = 1,
                            Nome = "Gin Tonica",
                            Preco = 30.00m
                        });
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Andar")
                        .HasColumnType("int")
                        .HasColumnName("andar");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int")
                        .HasColumnName("capacidade");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("numero");

                    b.Property<decimal>("PrecoDiaria")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_diaria");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("quartos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Andar = 1,
                            Ativo = true,
                            Capacidade = 2,
                            IdEmpresa = 1,
                            Numero = "101",
                            PrecoDiaria = 250.00m,
                            Status = "Disponivel",
                            Tipo = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Andar = 1,
                            Ativo = true,
                            Capacidade = 2,
                            IdEmpresa = 1,
                            Numero = "102",
                            PrecoDiaria = 250.00m,
                            Status = "Disponivel",
                            Tipo = "Standard"
                        },
                        new
                        {
                            Id = 3,
                            Andar = 1,
                            Ativo = true,
                            Capacidade = 3,
                            IdEmpresa = 1,
                            Numero = "103",
                            PrecoDiaria = 400.00m,
                            Status = "Disponivel",
                            Tipo = "Luxo"
                        },
                        new
                        {
                            Id = 4,
                            Andar = 1,
                            Ativo = true,
                            Capacidade = 4,
                            IdEmpresa = 1,
                            Numero = "104",
                            PrecoDiaria = 600.00m,
                            Status = "Disponivel",
                            Tipo = "Suite"
                        },
                        new
                        {
                            Id = 5,
                            Andar = 2,
                            Ativo = true,
                            Capacidade = 2,
                            IdEmpresa = 1,
                            Numero = "201",
                            PrecoDiaria = 280.00m,
                            Status = "Disponivel",
                            Tipo = "Standard"
                        },
                        new
                        {
                            Id = 6,
                            Andar = 2,
                            Ativo = true,
                            Capacidade = 3,
                            IdEmpresa = 1,
                            Numero = "202",
                            PrecoDiaria = 450.00m,
                            Status = "Disponivel",
                            Tipo = "Luxo"
                        },
                        new
                        {
                            Id = 7,
                            Andar = 2,
                            Ativo = true,
                            Capacidade = 3,
                            IdEmpresa = 1,
                            Numero = "203",
                            PrecoDiaria = 450.00m,
                            Status = "Disponivel",
                            Tipo = "Luxo"
                        },
                        new
                        {
                            Id = 8,
                            Andar = 2,
                            Ativo = true,
                            Capacidade = 4,
                            IdEmpresa = 1,
                            Numero = "204",
                            PrecoDiaria = 650.00m,
                            Status = "Disponivel",
                            Tipo = "Suite"
                        });
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_checkin");

                    b.Property<DateTime>("DataCheckout")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_checkout");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdHospede")
                        .HasColumnType("int")
                        .HasColumnName("id_hospede");

                    b.Property<int>("IdQuarto")
                        .HasColumnType("int")
                        .HasColumnName("id_quarto");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdHospede");

                    b.HasIndex("IdQuarto");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@pousada.com",
                            IdEmpresa = 1,
                            Nome = "Administrador",
                            Role = "Admin",
                            SenhaHash = "$2a$11$uPCh9a1iJzHlzjuoZgtGIeVjCloKvE4fhPXEysmJpwqIiQI0M/51K"
                        });
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.CategoriaCardapio", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.Empresa", "Empresa")
                        .WithMany("CategoriasCardapio")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Comanda", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Comandas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PousadaApp.Domain.Entities.Reserva", "Reserva")
                        .WithMany("Comandas")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Hospede", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Hospedes")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.ItemComanda", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.Comanda", "Comanda")
                        .WithMany("Itens")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PousadaApp.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensComanda")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Produto", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.CategoriaCardapio", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PousadaApp.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Produtos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Quarto", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Quartos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PousadaApp.Domain.Entities.Hospede", "Hospede")
                        .WithMany("Reservas")
                        .HasForeignKey("IdHospede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PousadaApp.Domain.Entities.Quarto", "Quarto")
                        .WithMany("Reservas")
                        .HasForeignKey("IdQuarto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Hospede");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PousadaApp.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.CategoriaCardapio", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Comanda", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("CategoriasCardapio");

                    b.Navigation("Comandas");

                    b.Navigation("Hospedes");

                    b.Navigation("Produtos");

                    b.Navigation("Quartos");

                    b.Navigation("Reservas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Hospede", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensComanda");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Quarto", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PousadaApp.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("Comandas");
                });
#pragma warning restore 612, 618
        }
    }
}
